# EditorConfig not taken into account.
# editorConfig: true
singleQuote: true
useTabs: true

# TODO: try
# htmlWhitespaceSensitivity: ignore

overrides:
  - files: ['*.md', '*.yaml', '*.json', '.*rc*']
    options:
      useTabs: false
